[project]
name = "cora-datadevelopment"
version = "1.0.0"
dependencies = [
    "requests",
    "requests-toolbelt",
    "requests-mock",
    "tqdm",
    "pytest",
    "pytest-cov",
    "pytest-watcher",
    "fabric"
]
license = "GPL-3.0"

[project.scripts]
publishers-import = "scripts.publishers_import:main"
funders-import = "scripts.funders_import:main"
journals-import = "scripts.journals_import:main"
outputs-import = "scripts.outputs_import:main"
outputs-export = "scripts.outputs_export:main"
outputs-testdata-create = "scripts.outputs_testdata_create:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["test"]