[project]
name = "cora-datadevelopment"
version = "1.0.0"
dependencies = [
    "requests",
    "requests-toolbelt",
    "requests-mock",
    "tqdm",
    "pytest",
    "pytest-cov",
    "pytest-watcher",
    "psycopg2-binary",
    "freezegun",
    "rich",
    "python-dotenv"
]
license = "GPL-3.0"

[project.scripts]
outputs-import = "scripts.outputs_import:main"
outputs-export = "scripts.outputs_export:main"
outputs-testdata-create = "scripts.outputs_testdata_create:main"
organisations-migrate = "scripts.organisations_migrate:main"
diva-migrate = "scripts.diva_migrate:main"
create-validation-types = "scripts.create_new_validation_types:main"
delete-validation-types = "scripts.delete_new_validation_types:main"
analyze-errors = "scripts.util.analyze_errors:main"
delete-all-records-of-type = "scripts.util.remove_all_records_of_type:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["test"]