[project]
name = "cora-datadevelopment"
version = "1.0.0"
dependencies = [
    "requests",
    "requests-toolbelt",
    "requests-mock",
    "tqdm",
    "pytest",
    "pytest-cov",
    "pytest-watcher",
    "fabric"
]
license = "GPL-3.0"

[project.scripts]
outputs-migrate = "scripts.outputs_migrate:main"
outputs-testdata-create = "scripts.outputs_testdata_create:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["test"]